namespace = "GyDX55sFnbr9yCB-mPyXsy4kAUPUY8ftpWX62s6UcnvfIQ=="
local_channels = ['uPMU_4/L1']
reference_channels = ['uPMU_0/L1']
entity = 'lpbctest.ent'
wavemq = '127.0.0.1:4516'
rate = 2  # number of seconds between calls to 'step'
name = 'lpbctest' # node ID
spbc = 'spbctest'
